SUPABASE_URL = "https://xkxtwnqfueoppcryftax.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreHR3bnFmdWVvcHBjcnlmdGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTUwMjIsImV4cCI6MjA3MTEzMTAyMn0.Cz7nDgOLV9VqciPk9vTeJDyF891b8jbJzr0RXKdLnFU"
